//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phone
    {
        public int ID { get; set; }
        public string Country_Code { get; set; }
        public int Phone_Number { get; set; }
        public string Email { get; set; }
    
        public virtual Member Member { get; set; }
    }
}
