//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Picture
    {
        public int ID { get; set; }
        public string Picture_Names { get; set; }
        public byte[] Picture1 { get; set; }
        public int unique_House { get; set; }
    }
}
