//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seek
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Seek()
        {
            this.Member = new HashSet<Member>();
        }
    
        public int Seek_ID { get; set; }
        public int Budget_Min { get; set; }
        public int Budget_Max { get; set; }
        public string City { get; set; }
        public string Constraints { get; set; }
        public string Neighbourhood { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Member> Member { get; set; }
    }
}
